### ISSUE TITLE
RuntimeError: Task got Future <Future pending> attached to a different loop

### ISSUE THREAD

**Issue by MelqonyanG** [Aloomaio/async-hvac#19]
I have the following function:
`async def get_credentials(project_id):
    return await client.is_initialized()`

and I call this function from a multithreaded project simultaneously. 

`import asyncio
import multiprocessing
from threadpool import ThreadPool, makeRequests
processes = 1
thread_num = 4
from vault.vault import get_credentials

def on_start(num):
    loop = asyncio.get_event_loop_policy().new_event_loop()
    coro = get_credentials("test-46cb8")
    if coro:
        future = asyncio.ensure_future(coro, loop=loop)
        r = loop.run_until_complete(future)
        print(r)
    print('end')

def thread_web_socket():
    pool_list = ThreadPool(thread_num)
    num = list()
    for ir in range(thread_num):
        num.append(ir)
    requests = makeRequests(on_start, num)
    [pool_list.putRequest(req) for req in requests]
    pool_list.wait()

if __name__ == "__main__":
    pool = multiprocessing.Pool(processes=processes)
    for i in range(processes):
        pool.apply_async(thread_web_socket)
    pool.close()
    pool.join()`

but I got results from get_credentials only for the first call. After that it returns RuntimeError: Task got Future <Future pending> attached to a different loop:
`Traceback (most recent call last):
  File "/home/gayane/.virtualenvs/envs/hoory-env/lib/python3.6/site-packages/threadpool.py", line 158, in run
    result = request.callable(*request.args, **request.kwds)
  File "threadstest.py", line 21, in on_start
    r = loop.run_until_complete(future)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/gayane/workspace/hoory_ml/vault/vault.py", line 63, in get_df_project_credentials
    return await client.is_initialized()
  File "/home/gayane/.virtualenvs/envs/hoory-env/lib/python3.6/site-packages/async_hvac/v1/__init__.py", line 102, in is_initialized
    return (await (await self._get('/v1/sys/init')).json())['initialized']
  File "/home/gayane/.virtualenvs/envs/hoory-env/lib/python3.6/site-packages/async_hvac/v1/__init__.py", line 1633, in __request
    proxy=self._proxies, **kwargs)
  File "/home/gayane/.virtualenvs/envs/hoory-env/lib/python3.6/site-packages/aiohttp/client.py", line 366, in _request
    timeout=timeout
  File "/home/gayane/.virtualenvs/envs/hoory-env/lib/python3.6/site-packages/aiohttp/connector.py", line 445, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/gayane/.virtualenvs/envs/hoory-env/lib/python3.6/site-packages/aiohttp/connector.py", line 757, in _create_connection
    req, traces, timeout)
  File "/home/gayane/.virtualenvs/envs/hoory-env/lib/python3.6/site-packages/aiohttp/connector.py", line 843, in _create_direct_connection
    traces=traces), loop=self._loop)
RuntimeError: Task <Task pending coro=<get_df_project_credentials() running at /home/gayane/workspace/hoory_ml/vault/vault.py:63> cb=[_run_until_complete_cb() at /usr/lib/python3.6/asyncio/base_events.py:196]> got Future <Future pending> attached to a different loop
`

I have tried to call the function in different ways but to no avail. Please help to fix this issue

**Comment by captain-kark** [comment]
```py
async def get_credentials(project_id):
      return await client.is_initialized()
```

This `client` might be already instantiated without specifying any loop, [defaulting to the main loop](https://github.com/Aloomaio/async-hvac/blob/e87b6abe969295baa4283acbdf9f03c87d1242b5/async_hvac/__init__.py#L43), perhaps?

If so, create a new client and pass in a `loop` from the thread.

Otherwise you could try running `sync`, since that appears to schedule "async" events [into a thread pool anyway](https://github.com/Aloomaio/async-hvac/blob/e87b6abe969295baa4283acbdf9f03c87d1242b5/async_hvac/__init__.py#L13). Threads spawning threads aside, this seems like it could work.
